// Define translations for the profile section

export const profileTranslations = {
  en: {
    title: "I'm Rachid, a curious soul\nand a software engineer\nfrom Morocco 🇲🇦 ✌️",
    tldr: "About Me",
    paragraph1: "I'm grounded in Casablanca, but always mentally somewhere between Tokyo, Berlin, and the nearest API documentation. I haven't left Morocco (yet), but I travel through curiosity. I'm deeply fascinated by how things work — from the way music hits emotions to the invisible logic behind great technology. If there's a new tool, platform, or gadget, I'm probably already down the rabbit hole learning how it ticks.",
    paragraph2: "Freedom means a lot to me — freedom to think, create, move, and grow. Whether it's building something in code, sketching ideas, or imagining my next adventure, I chase that feeling. I believe tech should empower people, not confuse them. Music is my daily fuel — whether it's Moroccan chaabi or lo-fi beats from halfway across the world. I dream of seeing the world someday, not just to visit, but to connect with the stories, people, and designs that shape it.",
    paragraph3: "Things that don't spark joy? Noise without meaning, being told \"that's just how it is,\" and when headphones die mid-song. Things that do? Late-night learning sprees, beautiful design, and the feeling when your code finally works. I'm not a pessimist. I'm just deeply observant. And always building — ideas, skills, and a life filled with curiosity."
  },
  ru: {
    title: "Я Рашид, любознательная душа\nи технический энтузиаст\nиз Марокко 🇲🇦 ✌️",
    tldr: "Обо мне",
    paragraph1: "Я живу в Касабланке, но мысленно всегда где-то между Токио, Берлином и ближайшей документацией API. Я еще не покидал Марокко, но путешествую через любознательность. Меня глубоко увлекает то, как работают вещи — от того, как музыка влияет на эмоции, до невидимой логики, стоящей за великолепными технологиями. Если есть новый инструмент, платформа или гаджет, я, вероятно, уже погружаюсь в изучение того, как он работает.",
    paragraph2: "Свобода значит для меня очень много — свобода мыслить, создавать, двигаться и расти. Будь то создание чего-то в коде, набросок идей или представление моего следующего приключения, я стремлюсь к этому чувству. Я верю, что технологии должны расширять возможности людей, а не запутывать их. Музыка — мое ежедневное топливо, будь то марокканский шааби или ло-фай биты с другого конца света. Я мечтаю когда-нибудь увидеть мир, не просто посетить его, а соединиться с историями, людьми и дизайнами, которые его формируют.",
    paragraph3: "Что не приносит радости? Шум без смысла, когда говорят \"так уж устроено\", и когда наушники умирают посреди песни. Что приносит? Ночные учебные марафоны, красивый дизайн и чувство, когда твой код наконец работает. Я не пессимист. Я просто глубоко наблюдательный. И всегда строю — идеи, навыки и жизнь, наполненную любознательностью."
  },
  fr: {
    title: "Je suis Rachid, une âme curieuse\net un software engineer\ndu Maroc 🇲🇦 ✌️",
    tldr: "À propos de moi",
    paragraph1: "Je suis basé à Casablanca, mais mentalement toujours quelque part entre Tokyo, Berlin et la documentation API la plus proche. Je n'ai pas encore quitté le Maroc, mais je voyage par la curiosité. Je suis profondément fasciné par le fonctionnement des choses — de la façon dont la musique touche les émotions à la logique invisible derrière les grandes technologies. S'il y a un nouvel outil, une plateforme ou un gadget, je suis probablement déjà en train d'explorer comment il fonctionne.",
    paragraph2: "La liberté signifie beaucoup pour moi — liberté de penser, de créer, de bouger et de grandir. Que ce soit construire quelque chose en code, esquisser des idées ou imaginer ma prochaine aventure, je poursuis ce sentiment. Je crois que la technologie devrait donner du pouvoir aux gens, pas les confondre. La musique est mon carburant quotidien — que ce soit le chaabi marocain ou les beats lo-fi de l'autre bout du monde. Je rêve de voir le monde un jour, pas seulement pour visiter, mais pour me connecter avec les histoires, les personnes et les designs qui le façonnent.",
    paragraph3: "Les choses qui ne procurent pas de joie ? Le bruit sans signification, qu'on me dise \"c'est comme ça\", et quand les écouteurs meurent au milieu d'une chanson. Les choses qui en procurent ? Les séances d'apprentissage nocturnes, le beau design, et la sensation quand votre code fonctionne enfin. Je ne suis pas pessimiste. Je suis simplement profondément observateur. Et toujours en train de construire — des idées, des compétences et une vie remplie de curiosité."
  }
};
